FROM ubuntu:latest
LABEL maintainer "asd147asd147@naver.com"
RUN apt-get update
RUN apt-get install yarn  -y
RUN apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install nodejs -y
RUN apt-get install build-essential -y